Enhance CI with code quality checks and test reporting
Added Revive and Staticcheck actions for code quality checks. Updated test command to use gotestsum and added a step to publish test reports.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -15,14 +15,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-
+ 
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.20'
+        
+    - name: Revive Action
+      uses: morphy2k/revive-action@v2.4.1
+
+    - name: Staticcheck
+      uses: dominikh/staticcheck-action@v1.3.0
+
 
     - name: Build
       run: go build -v ./...
 
     - name: Test
-      run: go test -v ./...
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
